### ISSUE TITLE
GenTB suggestions

### ISSUE THREAD

**Issue by SBassler** [farhat-lab/gentb-site#121]
![image](https://user-images.githubusercontent.com/38661384/39143406-d57d387a-46fb-11e8-84ba-3f46e576afec.png)
I would suggest more space between the top of the plot and the legend

![image](https://user-images.githubusercontent.com/38661384/39143655-81e12004-46fc-11e8-9a8c-4641cf99a1a9.png)
English names would be very helpful if you are not familiar with the region

Nevertheless, it looks really nice, good job!

**Comment by mahafarhat** [comment]
Task for Mohib

**Comment by mjafri118** [comment]
@doctormo 

Uploading the enriched VCF files are proving a bit problematic. What was the command within manage.py we need to run in order to complete the import? 

Testing the following: 
**Loaddata**
_Needs something else to be specified in database._

**Load_map_data**
_Countries/locations are iteratively returned as “Saved: Te Anau.” Map not updated._

**Process_uploads**
_Hangs for a moment before nothing returned to console. Map/data not updated._

**Comment by doctormo** [comment]
Was there no error such as `No pipeline 'VCF_TO_VAR' which is required.` when running `process_uploads`?

**Comment by mjafri118** [comment]
@doctormo Nope. Just some hangtime and then a new line. Using the VCF files in Dropbox we got on Friday.

**Comment by doctormo** [comment]
Are you able to debug the problem, or do you need some help?

**Comment by mjafri118** [comment]
Some help would be appreciated. I managed to get the uploads to this point. If process_uploads is the command I need to invoke, then some debugging help at this point would be great. Attached: 
![image](https://user-images.githubusercontent.com/31643580/46433216-4972b280-c71e-11e8-9393-e9fb311eee87.png)

**Comment by mahafarhat** [comment]
@doctormo were the top mapping cosmetic suggestions addressed? if so let's close

**Comment by doctormo** [comment]
Yep, fixed.
