### ISSUE TITLE
Maps designs

### ISSUE THREAD

**Issue by doctormo** [farhat-lab/gentb-site#125]
- [ ]  DESIGN - Make sure highlighted lucus blocks point to the list of possible mutations correctly.
- [ ]  DESIGN - Make sure there is positional flow between elements
- [ ]  DATA - Make sure Country, Drug and Lineage limits the Locus list and mutations lists
- [ ]  DATA - Make sure empty mutations do not show, to limit the selection of null elements.
- [ ]  DESIGN - Try and make the mutations map remain when selecting a new country or other data and simply update it.

**Comment by mahafarhat** [comment]
Task for Mohib

**Comment by mahafarhat** [comment]
Assigned to phanaj with an update on pending tasks in order of importance:
  DESIGN - Make sure highlighted locus blocks (DNA symbol) limits list of possible mutations correctly (in the mutations tab below)
  DESIGN - In the mutations tab, allow search for different patterns in the mutation name separated by spaces. For example allow search for S450L rpoB, instead of now requiring S450L_rpoB (exact single pattern).
  DATA - Make sure empty mutations do not show, to limit the selection of null elements.
  
Mostly achieved below: (doctormo can verify)
DESIGN - Make sure there is positional flow between elements
DATA - Make sure Country, Drug and Lineage limits the Locus list and mutations lists
DESIGN - Try and make the mutations map remain when selecting a new country or other data and simply update it.

**Comment by mahafarhat** [comment]
@phanaj do you still have time to commit to this task, the mutations display in the maps is currently broken and this is high priority. If you are no longer available please let us / @doctormo know.

**Comment by phanaj** [comment]
Oops very sorry @mahafarhat , I was in/out of jaw surgery and missed this last message. I've just added a quick commit which fixes the mutations display. I'll next ensure that the remaining fields filter mutations properly

**Comment by mahafarhat** [comment]
Issue still pending

**Comment by phanaj** [comment]
I don't believe the changes have gone live yet

**Comment by doctormo** [comment]
The changes are live now.
