### ISSUE TITLE
Implement user feedback of error and quality for other pipelines e.g. single ended pipeline, VCF pipeline

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#233]
At the moment when single-ended, or VCF file jobs fail little to no user feedback of error is given to the user. We need to implement the same changes we did for paired end pipelines

**Comment by doctormo** [comment]
Do you mean add the quality control flag to the single end and vcf pipeline jobs? This checkbox but for some of those pipeline jobs?

![Screenshot from 2021-04-15 13-35-32](https://user-images.githubusercontent.com/589384/114913688-7c1dbb80-9def-11eb-81d4-d1aa758b15ad.png)

Otherwise, I'm not sure. There's nothing in the code that's special to pair-ended jobs at the moment.

**Comment by mahafarhat** [comment]
I'm referring to the fact that the program error message is not displayed to the user when a program step fails. e.g. if a job fails quality control they just get a generic job failed for these two pipelines.

**Comment by doctormo** [comment]
I don't understand Maha. Sorry. I've checked the quality control information and it seems to all be correct.

Can you explain with the screenshot?
