### ISSUE TITLE
Clean up pipeline and program descriptions

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#235]
Matthias let's review the pipeline and program descriptions to keep in mind that these are user facing. Simplify and shorten where ever possible for all user facing pipelines.

**Comment by mgro** [comment]
@eford8 I've prepared updated program descriptions - updating the names will be a great way for your to learn navigate among the program in the admin interface.

**Comment by mahafarhat** [comment]
@mgro is this resolved? please close the issue if it is

**Comment by mgro** [comment]
Yes it is resolved – but I can’t close issues (you or Martin would need to do this)

From: Maha ***@***.***>
Date: Thursday, August 19, 2021 at 8:19 PM
To: farhat-lab/gentb-site ***@***.***>
Cc: Groeschel, Matthias ***@***.***>, Mention ***@***.***>
Subject: Re: [farhat-lab/gentb-site] Clean up pipeline and program descriptions (#235)

@mgro<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mgro&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=BBpXOEr_fGPHkgTDVGuJu78Y8pse-v9zHJOXDjeIxjbSb2oijEmdXvQ-8ZN6u04U&m=1m9O1oK5OHjwCpXQPPDPX0U-7lYve-YkHzGUTf7u9E8&s=XhtRgbslX1trZwKLSztV0fr0bBl7fUG9ZQUNdKxDdvk&e=> is this resolved? please close the issue if it is

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_farhat-2Dlab_gentb-2Dsite_issues_235-23issuecomment-2D902137822&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=BBpXOEr_fGPHkgTDVGuJu78Y8pse-v9zHJOXDjeIxjbSb2oijEmdXvQ-8ZN6u04U&m=1m9O1oK5OHjwCpXQPPDPX0U-7lYve-YkHzGUTf7u9E8&s=oNW9UUiohRyWqQV8LL7ynb4-9PeB9X5gZ9fIba-Zu1k&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFOA3IDOJBG76G7SFGVDJ33T5VDKHANCNFSM427VKGGA&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=BBpXOEr_fGPHkgTDVGuJu78Y8pse-v9zHJOXDjeIxjbSb2oijEmdXvQ-8ZN6u04U&m=1m9O1oK5OHjwCpXQPPDPX0U-7lYve-YkHzGUTf7u9E8&s=zqeKxOOz9ZywgK_LWWB0BegEr73znqIZU5j8e-Z1QqQ&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=BBpXOEr_fGPHkgTDVGuJu78Y8pse-v9zHJOXDjeIxjbSb2oijEmdXvQ-8ZN6u04U&m=1m9O1oK5OHjwCpXQPPDPX0U-7lYve-YkHzGUTf7u9E8&s=jAVYVcUFSQR0cfSbZA4bh8EqUMOKrdINkowizxTogO0&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=BBpXOEr_fGPHkgTDVGuJu78Y8pse-v9zHJOXDjeIxjbSb2oijEmdXvQ-8ZN6u04U&m=1m9O1oK5OHjwCpXQPPDPX0U-7lYve-YkHzGUTf7u9E8&s=Giq-vCF6T0TC_DsP_eDw_xYD48wWCmlXJjiVebLB7pM&e=>.
